/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "humidityStorage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(smart_home_StoreHumidityRequest, smart_home_StoreHumidityRequest, AUTO)


PB_BIND(smart_home_StoreHumidityReply, smart_home_StoreHumidityReply, AUTO)


PB_BIND(smart_home_GetActiveSensorsRequest, smart_home_GetActiveSensorsRequest, AUTO)


PB_BIND(smart_home_GetActiveSensorsReply, smart_home_GetActiveSensorsReply, AUTO)



